language: r
sudo: false
cache:
  - cargo
  - packages
addons:
  apt:
    packages:
      - oracle-java8-installer
      - clang
env:
  - NEO4J_VERSION=3.2.5
  - NEO4J_VERSION=3.0.4
  - NEO4J_VERSION=2.3.6
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.15.1
  - . ~/.cargo/env
  - . ./build-libneo4j-client.sh
r_github_packages:
  - hadley/testthat
r_packages:
  - roxygen2
script: make test_travis