language: r
sudo: false
cache:
  - cargo
  - packages
os:
  - linux
  - osx
addons:
  # only affects Linux
  apt:
    packages:
      - oracle-java8-installer
      - clang
env:
  - NEO4J_VERSION=3.2.5
  - NEO4J_VERSION=3.0.4
  - NEO4J_VERSION=2.3.6
before_install: . install_deps.sh
r_github_packages:
  - hadley/testthat
r_packages:
  - roxygen2
script: make test_travis