language: r
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
r_github_packages:
  - hadley/testthat
r_packages:
  - roxygen2
script: make test_all