// Generated by using rustinr::rustrize() -> do not edit by hand

use super::*;

#[no_mangle]
pub extern "C" fn rustr_open_graph_internal(uri : SEXP, username : SEXP, password : SEXP)->SEXP{

 let uri_ : CString = unwrapr!( CString::rnew(uri) );

let username_ : CString = unwrapr!( CString::rnew(username) );

let password_ : CString = unwrapr!( CString::rnew(password) );
 let res  = unwrapr!( open_graph_internal(uri_,username_,password_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

