[package]
name = "rustlib"
version = "0.1.0"
build = "build.rs"

[dependencies]
rustr = "0.1"
errno = "0.2"

[build-dependencies]
bindgen = "0.26"

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]
