# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initNeo4j <- function() {
    invisible(.Call('_RNeo4j_initNeo4j', PACKAGE = 'RNeo4j'))
}

cleanupNeo4j <- function() {
    invisible(.Call('_RNeo4j_cleanupNeo4j', PACKAGE = 'RNeo4j'))
}

startGraph <- function(url, username = "neo4j", password = "neo4j") {
    .Call('_RNeo4j_startGraph', PACKAGE = 'RNeo4j', url, username, password)
}

cypherInternal <- function(graphSexp, query, args, names) {
    .Call('_RNeo4j_cypherInternal', PACKAGE = 'RNeo4j', graphSexp, query, args, names)
}

